import type { NextPage } from "next";
import Head from "next/head";

import Banner from "../components/Banner";
// import Footer from "../components/Footer";
// import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MZN App Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />

      {/* <div className={styles.container}>
        <Footer />
      </div> */}
    </>
  );
};

export default Home;
